# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 152308f4c4c5a938262e5f9270cb1288719e30d525d7b7fe475ea96e1d5dd1879a324928153067e2ef73d9e3135f71500fe9ad5f2ea357d826268fcc0725a175

test:
  secret_key_base: 65d8dfe3b276dcfc7d8094b4ebabf0b4aec29f00c7b68db234421d3a58d2a698d9d35d8e9c036b8e5096aa1f2809ac04cb98b58cebb2eed655770ad41ce645e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
